apiVersion: apps/v1
kind: Deployment # This is for Deployment, has also another value like Service
metadata:
  labels: # labels value [app: spring-test-app] must be matched with matchLabels value
    app: spring-test-app
  name: spring-test-app
spec:
  replicas: 2 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: spring-test-app
  template:
    metadata:
      labels:
        app: spring-test-app
    spec:
      containers:
        - name: spring-test-app
          image: spring-boot-test # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
